// <auto-generated />
using System;
using ChapanakitCare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChapanakitCare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AdvanceLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balance_after");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balance_before");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<long>("EntryOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entry_order");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("member_id");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SourceDeathCaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_death_case_id");

                    b.Property<Guid?>("SourceResetBatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_reset_batch_id");

                    b.Property<int>("UnitsDelta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("units_delta");

                    b.HasKey("Id");

                    b.HasIndex("SourceDeathCaseId");

                    b.HasIndex("SourceResetBatchId");

                    b.HasIndex("MemberId", "EntryOrder")
                        .IsUnique();

                    b.ToTable("advance_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_advance_ledger_entries_arithmetic", "balance_before + units_delta = balance_after");

                            t.HasCheckConstraint("ck_advance_ledger_entries_source", "(entry_type = 'death_contribution' AND source_death_case_id IS NOT NULL AND source_reset_batch_id IS NULL) OR (entry_type = 'reset_to_30' AND source_reset_batch_id IS NOT NULL AND source_death_case_id IS NULL) OR (entry_type IN ('opening_30', 'correction', 'resignation_refund'))");

                            t.HasCheckConstraint("ck_advance_ledger_entries_type", "entry_type IN ('opening_30', 'death_contribution', 'reset_to_30', 'correction', 'resignation_refund')");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AdvanceResetBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<string>("ConfirmedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by");

                    b.Property<int>("DeathsSincePreviousReset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths_since_previous_reset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<Guid?>("PreviousResetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_reset_id");

                    b.Property<string>("ResetNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_no");

                    b.Property<int>("TargetUnits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_units");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PreviousResetId");

                    b.HasIndex("ResetNo")
                        .IsUnique();

                    b.ToTable("advance_reset_batches", null, t =>
                        {
                            t.HasCheckConstraint("ck_advance_reset_batches_trigger", "trigger_type IN ('manual', 'month_start', 'death_threshold')");

                            t.HasCheckConstraint("ck_advance_reset_batches_values", "target_units >= 0 AND deaths_since_previous_reset >= 0");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AdvanceResetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balance_after");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balance_before");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ledger_entry_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("member_id");

                    b.Property<Guid>("ResetBatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_batch_id");

                    b.Property<int>("UnitsDelta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("units_delta");

                    b.HasKey("Id");

                    b.HasIndex("LedgerEntryId")
                        .IsUnique();

                    b.HasIndex("MemberId");

                    b.HasIndex("ResetBatchId", "MemberId")
                        .IsUnique();

                    b.ToTable("advance_reset_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_advance_reset_lines_arithmetic", "balance_before + units_delta = balance_after");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("app_version");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_name");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_id");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("OperationId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AuditFieldChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("audit_event_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field_name");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_sensitive");

                    b.Property<string>("NewValueDisplay")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_value_display");

                    b.Property<string>("OldValueDisplay")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_value_display");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId");

                    b.ToTable("audit_field_changes", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_field_changes_sensitive", "is_sensitive IN (0, 1)");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_automatic");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_version");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.HasKey("Id");

                    b.ToTable("backup_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_backup_runs_automatic", "is_automatic IN (0, 1)");

                            t.HasCheckConstraint("ck_backup_runs_sha", "length(sha256) = 64");

                            t.HasCheckConstraint("ck_backup_runs_size", "file_size >= 0");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.DeathBeneficiarySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DeathCaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("death_case_id");

                    b.Property<string>("District")
                        .HasColumnType("TEXT")
                        .HasColumnName("district");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("HouseNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("house_no");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT")
                        .HasColumnName("mobile");

                    b.Property<string>("Moo")
                        .HasColumnType("TEXT")
                        .HasColumnName("moo");

                    b.Property<string>("PersonalIdCard")
                        .HasColumnType("TEXT")
                        .HasColumnName("personal_id_card");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT")
                        .HasColumnName("province");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT")
                        .HasColumnName("relationship");

                    b.Property<int>("ShareDenominator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("share_denominator");

                    b.Property<int>("ShareNumerator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("share_numerator");

                    b.Property<int>("SlotNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_no");

                    b.Property<string>("Subdistrict")
                        .HasColumnType("TEXT")
                        .HasColumnName("subdistrict");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("DeathCaseId", "SlotNo")
                        .IsUnique();

                    b.ToTable("death_beneficiary_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_death_beneficiary_snapshots_postal", "postal_code IS NULL OR length(postal_code) = 5");

                            t.HasCheckConstraint("ck_death_beneficiary_snapshots_share", "share_numerator = 1 AND share_denominator IN (1, 2)");

                            t.HasCheckConstraint("ck_death_beneficiary_snapshots_slot", "slot_no IN (1, 2)");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.DeathCalculation", b =>
                {
                    b.Property<Guid>("DeathCaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("death_case_id");

                    b.Property<int>("BeneficiaryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beneficiary_count");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("calculated_at_utc");

                    b.Property<int>("ContributorCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contributor_count");

                    b.Property<int>("DeceasedAdvanceUnits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deceased_advance_units");

                    b.Property<long>("DeceasedAdvanceValueSatang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deceased_advance_value_satang");

                    b.Property<long>("GrossCollectionSatang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gross_collection_satang");

                    b.Property<bool>("IsPayable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_payable");

                    b.Property<long>("NetCollectionSatang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("net_collection_satang");

                    b.Property<int>("ServiceFeeBasisPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_fee_basis_points");

                    b.Property<string>("ServiceFeeRoundingMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_fee_rounding_mode");

                    b.Property<long>("ServiceFeeSatang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_fee_satang");

                    b.Property<long>("TotalBenefitSatang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_benefit_satang");

                    b.Property<long>("WelfarePerMemberSatang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("welfare_per_member_satang");

                    b.HasKey("DeathCaseId");

                    b.ToTable("death_calculations", null, t =>
                        {
                            t.HasCheckConstraint("ck_death_calculations_arithmetic", "gross_collection_satang - service_fee_satang = net_collection_satang AND net_collection_satang + deceased_advance_value_satang = total_benefit_satang");

                            t.HasCheckConstraint("ck_death_calculations_counts", "contributor_count >= 0 AND beneficiary_count BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_death_calculations_fee", "service_fee_basis_points BETWEEN 0 AND 10000 AND service_fee_satang >= 0");

                            t.HasCheckConstraint("ck_death_calculations_payable", "is_payable IN (0, 1)");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.DeathCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CauseOfDeathText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cause_of_death_text");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<string>("ConfirmedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by");

                    b.Property<int>("DaysSinceCoverage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("days_since_coverage");

                    b.Property<string>("DeathCaseNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("death_case_no");

                    b.Property<string>("DeathCertificateContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("death_certificate_content_type");

                    b.Property<DateOnly>("DeathCertificateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("death_certificate_date");

                    b.Property<string>("DeathCertificateFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("death_certificate_file_name");

                    b.Property<string>("DeathCertificateNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("death_certificate_no");

                    b.Property<byte[]>("DeathCertificatePdf")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("death_certificate_pdf");

                    b.Property<string>("DeathCertificateSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("death_certificate_sha256");

                    b.Property<long>("DeathCertificateSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("death_certificate_size");

                    b.Property<long>("DeathSequenceNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("death_sequence_no");

                    b.Property<string>("EligibilityResult")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eligibility_result");

                    b.Property<bool>("IsManualNonPayCase")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_manual_nonpay_case");

                    b.Property<string>("ManualNonPayReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("manual_nonpay_reason");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("member_id");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("record_state");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<DateOnly>("RecordedBusinessDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_business_date");

                    b.Property<int>("SettingsRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("settings_revision");

                    b.Property<string>("VoidReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("voided_at_utc");

                    b.Property<string>("VoidedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("voided_by");

                    b.HasKey("Id");

                    b.HasIndex("DeathCaseNo")
                        .IsUnique();

                    b.HasIndex("DeathSequenceNo")
                        .IsUnique();

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("death_cases", null, t =>
                        {
                            t.HasCheckConstraint("ck_death_cases_certificate_pdf", "death_certificate_size BETWEEN 1 AND 10485760 AND length(death_certificate_pdf) = death_certificate_size AND length(death_certificate_sha256) = 64");

                            t.HasCheckConstraint("ck_death_cases_eligibility", "eligibility_result IN ('before_coverage_zero', 'payable', 'manual_nonpay_zero')");

                            t.HasCheckConstraint("ck_death_cases_manual", "is_manual_nonpay_case IN (0, 1)");

                            t.HasCheckConstraint("ck_death_cases_reason", "is_manual_nonpay_case = 0 OR manual_nonpay_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_death_cases_state", "record_state IN ('confirmed', 'voided')");

                            t.HasCheckConstraint("ck_death_cases_void", "record_state <> 'voided' OR (voided_at_utc IS NOT NULL AND void_reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.DeathMemberSnapshot", b =>
                {
                    b.Property<Guid>("DeathCaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("death_case_id");

                    b.Property<int>("AdvanceUnitsBeforeDeath")
                        .HasColumnType("INTEGER")
                        .HasColumnName("advance_units_before_death");

                    b.Property<int?>("AgeAtDeath")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age_at_death");

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("application_date");

                    b.Property<DateOnly>("ApprovalDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_date");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<DateOnly>("CoverageStartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("coverage_start_date");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("district");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("GroupNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_no");

                    b.Property<string>("HouseNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("house_no");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT")
                        .HasColumnName("mobile");

                    b.Property<string>("Moo")
                        .HasColumnType("TEXT")
                        .HasColumnName("moo");

                    b.Property<string>("PersonalIdCard")
                        .HasColumnType("TEXT")
                        .HasColumnName("personal_id_card");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("province");

                    b.Property<string>("RunNo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("run_no");

                    b.Property<string>("Subdistrict")
                        .HasColumnType("TEXT")
                        .HasColumnName("subdistrict");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Under")
                        .HasColumnType("TEXT")
                        .HasColumnName("under");

                    b.HasKey("DeathCaseId");

                    b.ToTable("death_member_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_death_member_snapshots_run", "length(run_no) = 5");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AdvanceUnitsBalance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("advance_units_balance");

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("application_date");

                    b.Property<DateOnly>("ApprovalDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_date");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_by");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<DateOnly>("CoverageStartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("coverage_start_date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("district");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("GroupNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_no");

                    b.Property<string>("HouseNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("house_no");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT")
                        .HasColumnName("mobile");

                    b.Property<string>("Moo")
                        .HasColumnType("TEXT")
                        .HasColumnName("moo");

                    b.Property<string>("PersonalIdCard")
                        .HasColumnType("TEXT")
                        .HasColumnName("personal_id_card");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("province");

                    b.Property<string>("RunNo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("run_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Subdistrict")
                        .HasColumnType("TEXT")
                        .HasColumnName("subdistrict");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Under")
                        .HasColumnType("TEXT")
                        .HasColumnName("under");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PersonalIdCard")
                        .IsUnique()
                        .HasFilter("personal_id_card IS NOT NULL");

                    b.HasIndex("RunNo")
                        .IsUnique();

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("ck_members_archive", "archived_at_utc IS NULL OR archive_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_members_postal_code", "postal_code IS NULL OR length(postal_code) = 5");

                            t.HasCheckConstraint("ck_members_run_no_length", "length(run_no) = 5");

                            t.HasCheckConstraint("ck_members_status", "status IN ('normal', 'deceased', 'resigned')");

                            t.HasCheckConstraint("ck_members_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.MemberBeneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_by");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("District")
                        .HasColumnType("TEXT")
                        .HasColumnName("district");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("HouseNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("house_no");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("member_id");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT")
                        .HasColumnName("mobile");

                    b.Property<string>("Moo")
                        .HasColumnType("TEXT")
                        .HasColumnName("moo");

                    b.Property<string>("PersonalIdCard")
                        .HasColumnType("TEXT")
                        .HasColumnName("personal_id_card");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT")
                        .HasColumnName("province");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT")
                        .HasColumnName("relationship");

                    b.Property<int>("SlotNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_no");

                    b.Property<string>("Subdistrict")
                        .HasColumnType("TEXT")
                        .HasColumnName("subdistrict");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Under")
                        .HasColumnType("TEXT")
                        .HasColumnName("under");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "SlotNo")
                        .IsUnique()
                        .HasFilter("is_active = 1");

                    b.ToTable("member_beneficiaries", null, t =>
                        {
                            t.HasCheckConstraint("ck_member_beneficiaries_active", "is_active IN (0, 1)");

                            t.HasCheckConstraint("ck_member_beneficiaries_archive", "archived_at_utc IS NULL OR archive_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_member_beneficiaries_postal", "postal_code IS NULL OR length(postal_code) = 5");

                            t.HasCheckConstraint("ck_member_beneficiaries_slot", "slot_no IN (1, 2)");

                            t.HasCheckConstraint("ck_member_beneficiaries_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.MemberStatusEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_date");

                    b.Property<string>("FromStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("from_status");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("member_id");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("member_status_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_member_status_events_from", "from_status IS NULL OR from_status IN ('normal', 'deceased', 'resigned')");

                            t.HasCheckConstraint("ck_member_status_events_to", "to_status IN ('normal', 'deceased', 'resigned')");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("CycleKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cycle_key");

                    b.Property<int?>("DeathsSinceLatestReset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths_since_latest_reset");

                    b.Property<Guid?>("LatestResetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("latest_reset_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("TriggeredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("triggered_at_utc");

                    b.Property<DateOnly>("TriggeredBusinessDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("triggered_business_date");

                    b.HasKey("Id");

                    b.HasIndex("LatestResetId");

                    b.HasIndex("NotificationType", "CycleKey")
                        .IsUnique();

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_ack", "state <> 'acknowledged' OR acknowledged_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_notifications_state", "state IN ('active', 'acknowledged')");

                            t.HasCheckConstraint("ck_notifications_type", "notification_type IN ('month_start_reset', 'death_threshold')");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.NumberSequence", b =>
                {
                    b.Property<string>("SequenceKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("sequence_key");

                    b.Property<long>("NextValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_value");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("SequenceKey");

                    b.ToTable("number_sequences", null, t =>
                        {
                            t.HasCheckConstraint("ck_number_sequences_next", "next_value >= 0");

                            t.HasCheckConstraint("ck_number_sequences_width", "width > 0");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CoverageWaitDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("coverage_wait_days");

                    b.Property<int>("DeathWarningThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("death_warning_threshold");

                    b.Property<long?>("RegistrationFeeSatang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("registration_fee_satang");

                    b.Property<int>("ResetTargetUnits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reset_target_units");

                    b.Property<int>("ServiceFeeBasisPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_fee_basis_points");

                    b.Property<string>("ServiceFeeRoundingMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_fee_rounding_mode");

                    b.Property<int>("SettingsRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("settings_revision");

                    b.Property<int>("SpecialNonPayWindowDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("special_nonpay_window_days");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<long>("WelfarePerMemberSatang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("welfare_per_member_satang");

                    b.HasKey("Id");

                    b.ToTable("system_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_system_settings_fee", "service_fee_basis_points BETWEEN 0 AND 10000 AND (registration_fee_satang IS NULL OR registration_fee_satang >= 0)");

                            t.HasCheckConstraint("ck_system_settings_revision", "settings_revision >= 1");

                            t.HasCheckConstraint("ck_system_settings_singleton", "id = 1");

                            t.HasCheckConstraint("ck_system_settings_values", "welfare_per_member_satang > 0 AND reset_target_units >= 0 AND coverage_wait_days >= 0 AND special_nonpay_window_days >= 0 AND death_warning_threshold > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverageWaitDays = 180,
                            DeathWarningThreshold = 25,
                            ResetTargetUnits = 30,
                            ServiceFeeBasisPoints = 400,
                            ServiceFeeRoundingMode = "round_down_to_satang",
                            SettingsRevision = 1,
                            SpecialNonPayWindowDays = 365,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system_seed",
                            WelfarePerMemberSatang = 900L
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.ThaiAddressReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("district");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedSearch")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_search");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("province");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_version");

                    b.Property<string>("Subdistrict")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subdistrict");

                    b.HasKey("Id");

                    b.HasIndex("Subdistrict", "PostalCode")
                        .IsUnique();

                    b.ToTable("thai_address_reference", null, t =>
                        {
                            t.HasCheckConstraint("ck_thai_address_reference_active", "is_active IN (0, 1)");

                            t.HasCheckConstraint("ck_thai_address_reference_postal", "length(postal_code) = 5");
                        });
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.UiTablePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ColumnOrderJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("column_order_json");

                    b.Property<string>("ColumnWidthsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("column_widths_json");

                    b.Property<string>("HiddenColumnsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hidden_columns_json");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_key");

                    b.Property<string>("SortJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("sort_json");

                    b.Property<string>("TableKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("table_key");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VisibleComponentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("visible_components_json");

                    b.HasKey("Id");

                    b.HasIndex("ProfileKey", "TableKey")
                        .IsUnique();

                    b.ToTable("ui_table_preferences", (string)null);
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AdvanceLedgerEntry", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChapanakitCare.Domain.Entities.DeathCase", null)
                        .WithMany()
                        .HasForeignKey("SourceDeathCaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChapanakitCare.Domain.Entities.AdvanceResetBatch", null)
                        .WithMany()
                        .HasForeignKey("SourceResetBatchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AdvanceResetBatch", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.AdvanceResetBatch", null)
                        .WithMany()
                        .HasForeignKey("PreviousResetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AdvanceResetLine", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.AdvanceLedgerEntry", null)
                        .WithOne()
                        .HasForeignKey("ChapanakitCare.Domain.Entities.AdvanceResetLine", "LedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChapanakitCare.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChapanakitCare.Domain.Entities.AdvanceResetBatch", null)
                        .WithMany()
                        .HasForeignKey("ResetBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.AuditFieldChange", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.AuditEvent", null)
                        .WithMany()
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.DeathBeneficiarySnapshot", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.DeathCase", null)
                        .WithMany()
                        .HasForeignKey("DeathCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.DeathCalculation", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.DeathCase", null)
                        .WithOne()
                        .HasForeignKey("ChapanakitCare.Domain.Entities.DeathCalculation", "DeathCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.DeathCase", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.DeathMemberSnapshot", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.DeathCase", null)
                        .WithOne()
                        .HasForeignKey("ChapanakitCare.Domain.Entities.DeathMemberSnapshot", "DeathCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.MemberBeneficiary", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.MemberStatusEvent", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapanakitCare.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ChapanakitCare.Domain.Entities.AdvanceResetBatch", null)
                        .WithMany()
                        .HasForeignKey("LatestResetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
