<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ChapanakitCare</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChapanakitCare.Infrastructure\ChapanakitCare.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="App_Data\*.db*" />
    <Content Update="App_Data\demo-members.json" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
